### ISSUE TITLE
[Bug] Pf2e Not Rendering Properly

### ISSUE THREAD

**Issue by ChasarooniZ** [awarenet/foundry-roll-toasts#11]
![image](https://github.com/user-attachments/assets/b1505e7f-97c8-4279-bfe7-7b35c882dc20)

**Comment by awarenet** [comment]
Hi @ChasarooniZ - is this only the Disarm action or all actions?
I cannot reproduce this - 
![image](https://github.com/user-attachments/assets/28781cf0-95d0-48bc-b213-cf1a6fae8fd7)

**Comment by ChasarooniZ** [comment]
Uhh it seems to show up for any Skill Checks

**Comment by awarenet** [comment]
Yeah skills are still the same -sorry I really have no idea on PF2E so please feel free to point me to the character sheet buttons you are using :)
![image](https://github.com/user-attachments/assets/5eed36b4-72a8-4c10-858b-9d2a67e7a60e)
****

**Comment by awarenet** [comment]
Just checking @ChasarooniZ  what version of the module are you running?

**Comment by ChasarooniZ** [comment]
Uhh sorry unclear MB, it is specifically using actions in pf2e (IE skill checks that are actions)

For example this
[[/act disarm]]

**Comment by ChasarooniZ** [comment]
IIRC Pf2e HUD module ads an easy way to access them, but they're built in system functions that show up in most modules as well

**Comment by awarenet** [comment]
Uh I see now - why can't these hooks be consistent LOL.

**Comment by ChasarooniZ** [comment]
LOL

**Comment by awarenet** [comment]
Ok I've fixed it, will release under 1.2.2 shortly - I think this will with something else

**Comment by ChasarooniZ** [comment]
sick

**Comment by awarenet** [comment]
Done. download the update
