### ISSUE TITLE
[Request] Availability for other systems

### ISSUE THREAD

**Issue by SonofOrion42** [awarenet/foundry-roll-toasts#4]
Is it possible for this module to be adapted to other systems like Pathfinder 2e, for example? It looks incredibly useful as it is!

**Comment by awarenet** [comment]
Hi @SonofOrion42  - sure, I'll work on 2e next.

**Comment by awarenet** [comment]
Just to clarify - the module is system specific, but shouldn't be hard to adapt

**Comment by SonofOrion42** [comment]
Thank you! I look forward to it, along with many other 2e users, I'm sure. :)

**Comment by liquidsonic** [comment]
I would love to see this as well tbh, its super helpful for me as GM when doing lots of combat rolls <3

**Comment by awarenet** [comment]
Hey team 

I do have this ready but will need some PF2E experts to test it. 
Will sing out once it's available

**Comment by awarenet** [comment]
V1.2 is live - this includes an initial version for P2FE.
Please highlight any rolls I've missed (not a P2FE player :))
