### ISSUE TITLE
Toasts dont work

### ISSUE THREAD

**Issue by Sivernian** [awarenet/foundry-roll-toasts#5]
Hello, toasts dont work and... i dont really know why... i would like to see some advice, if it's ok to you. 

"Enabled toasts, show toasts when chat is active, show own and others rolls" is enabled
Foundry vtt Version 12 Stable 331
Dnd 3.3.1

**Comment by awarenet** [comment]
Hi @Sivernian 
Can you try changing a tick box then saving the settings. Once this is done refresh. I suspect there is a bug with the initial settings. 
Let me know your results:)

**Comment by BlackBadger777** [comment]
Hi @Sivernian, maybe you're having the same issues with initial setup as I had?
See https://github.com/awarenet/foundry-roll-toasts/issues/6#issue-2526322934, maybe that is of any use to you.

**Comment by awarenet** [comment]
Fixed in V1.2 - now live on foundry

**Comment by Sivernian** [comment]
@awarenet 

i dont know what did you do, but well... it works in new update! Sorry, i couldnt see your message :(
