### ISSUE TITLE
[Possible Bugs?] Roll Toasts requires setup process to work for each user

### ISSUE THREAD

**Issue by BlackBadger777** [awarenet/foundry-roll-toasts#6]
Setup:
Foundry v12 Build 331
DnD5e 3.3.1
Tested on Edge and Chrome browsers
Tested with all other modules disabled

First off, I've been looking for a long while for a module just like this one, so I'm super thrilled to have finally found one that does exactly what I need!! I'm really excited to finally have this feature in my game. Thank you so much for creating this module!

However, getting the module up and running required jumping through a few hoops I'm not sure are intentional: 

1) In order to activate roll toasts from _other_ users, each user has to go into the modules settings, save the settings (even if they haven't changed anything) and reload the browser. Only after the user has done so do _their_ rolls appear as toast for _other_ users, including the GM. 
Once you know that, it's relatively easy to direct each user to do this simple setup. However, it would be a cleaner setup process if the toasts were active immediately, without each user having to go through this process individually.

2) If a user disables 'Enable Toasts', their rolls do not show up as toasts to _any_ other users, not even the DM, I'm not sure this is intended behavior. In my view, it would make sense that disabling this setting would deactivate roll toasts for the individual user and not for other users. 

In relation to 2), might it be worthwhile to have a global GM setting allowing them to see roll toasts from all users regardless of their individual setup?

**Comment by awarenet** [comment]
#5 will fix the first issue thanks for the report @BlackBadger777.
Agree with the other point (2). Will add this as a tickbox to disable 'sending' of toasts for each player.

**Comment by awarenet** [comment]
Hi @BlackBadger777 in rereading your comment on point 2 - 
The user can select to completely enable or disable toasts for them and via the enable button.
The 'show own' and 'show other' function allows them to filter their own rolls or filter others rolls from the toasts.
I don't think I agree that every players rolls should send regardless.

**Comment by BlackBadger777** [comment]
First of all, thank you so much for the quick responses and the fix. I'll try out the update as soon as I can get back to work in my world, so later today or tomorrow. 

With regards to the issue at hand, I think it comes down to perspective - is it the user who "sends" these toasts and therefore is entitled to control whether other users get to see their rolls come up as toasts? Or is it the user who decides which rolls that they can already see in chat get "popped up" as toasts for them, regardless of who "sent" the roll/roll toast.

If you're point of view is that the rolls/roll toast are, in a way, "owned" by the user who made the roll, it's reasonable to allow them to deactivate sending their rolls as toasts to other players. In that case, nothing needs to change. 

I think my point of view is more on the other side of the spectrum. Especially for me as a GM, I see all rolls in chat anyway. And I am the one who has do adjudicate each roll as it comes in through the chat. So from that basis, it is my believe that it should be me as the GM who gets to decide whether I want to see my players' rolls as toasts, and not the player who gets to choose whether to send their rolls as toasts to me, since I get to see their roll anyway. 

I hope I made this difference in point of view clear. I totally understand if "my" point of view is not the direction you want to take this module in. So if you want to keep things as they are, feel free to close this issue, no harm done. The fact that you got the other issues addressed so quickly is already greatly appreciated! 👍

**Comment by awarenet** [comment]
Ok, I think you are correct. There should be an option to enable/disable the function globally, and then users can control what they see (not what they send).
Will implement in next release.

**Comment by awarenet** [comment]
Thanks @BlackBadger777  I have removed the enable option completely - GMs can manage enabling/disabling the plugin in the manage modules settings.
See v1.2.3
