### ISSUE TITLE
[Feature Request] Add roll toasts for Private GM Rolls

### ISSUE THREAD

**Issue by BlackBadger777** [awarenet/foundry-roll-toasts#7]
Setup:
Foundry v12 Build 331
DnD5e 3.3.1
Tested on Edge and Chrome browsers
Tested with all other modules disabled

Currently, Private GM Rolls from other users are not shown as roll toasts to the GM. Since GMs always see private rolls anyways, it would be nice to have them show up as roll toasts as well.

**Comment by awarenet** [comment]
Fixed in V1.2 - now live on foundry

**Comment by awarenet** [comment]
Added in v1.2.1 for P2FE and DnD 5e
